# Generated by Django 2.1.3 on 2018-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.CharField(default='', max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ADOPTADO', 'ADOPTADO'), ('RESCATADO', 'RESCATADO'), ('DISPONIBLE', 'DISPONIBLE')], max_length=10)),
            ],
        ),
    ]
